-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2021-12-26 23:01:17 ICT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cart (
    cart_id     INTEGER NOT NULL,
    total_price FLOAT DEFAULT 0 NOT NULL,
    create_at   TIMESTAMP DEFAULT current_timestamp,
    update_at   TIMESTAMP DEFAULT current_timestamp
);

ALTER TABLE cart ADD CONSTRAINT cart_pk PRIMARY KEY ( cart_id );

CREATE TABLE cart_product (
    id           INTEGER NOT NULL,
    cart_id      INTEGER NOT NULL,
    product_id   INTEGER NOT NULL,
    product_name VARCHAR2(200) NOT NULL,
    shop_id      INTEGER NOT NULL,
    quantity     INTEGER DEFAULT 0 NOT NULL,
    price        FLOAT DEFAULT 0 NOT NULL,
    create_at    TIMESTAMP DEFAULT current_timestamp NOT NULL,
    update_at    TIMESTAMP DEFAULT current_timestamp
);

ALTER TABLE cart_product ADD CONSTRAINT cart_product_pk PRIMARY KEY ( id );

CREATE TABLE "order" (
    order_id    INTEGER NOT NULL,
    cart_id     INTEGER NOT NULL,
    total_price FLOAT DEFAULT 0,
    create_at   TIMESTAMP DEFAULT current_timestamp,
    update_at   TIMESTAMP DEFAULT current_timestamp
);

ALTER TABLE "order" ADD CONSTRAINT order_pk PRIMARY KEY ( order_id );

CREATE TABLE product (
    product_id   INTEGER NOT NULL,
    product_name VARCHAR2(200) NOT NULL,
    shop_id      INTEGER NOT NULL,
    order_count  INTEGER DEFAULT 0,
    price        FLOAT DEFAULT 0 NOT NULL,
    status       SMALLINT DEFAULT 0 NOT NULL,
    stock        INTEGER DEFAULT 0 NOT NULL,
    total_rate   INTEGER DEFAULT 0,
    create_at    TIMESTAMP DEFAULT current_timestamp NOT NULL,
    update_at    TIMESTAMP DEFAULT current_timestamp
);

CREATE INDEX idx_status_price ON
    product (
        status
    ASC,
        price
    ASC );

CREATE INDEX idx_status_order_count ON
    product (
        status
    ASC,
        order_count
    ASC );

CREATE INDEX idx_status_total_rate ON
    product (
        status
    ASC,
        total_rate
    ASC );

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( product_id );

CREATE TABLE product_image (
    id         INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    image      VARCHAR2(200) NOT NULL,
    create_at  TIMESTAMP DEFAULT current_timestamp NOT NULL,
    update_at  TIMESTAMP DEFAULT current_timestamp
);

ALTER TABLE product_image ADD CONSTRAINT product_image_pk PRIMARY KEY ( id );

ALTER TABLE cart_product
    ADD CONSTRAINT cart_product_cart_fk FOREIGN KEY ( cart_id )
        REFERENCES cart ( cart_id );

ALTER TABLE "order"
    ADD CONSTRAINT order_cart_fk FOREIGN KEY ( cart_id )
        REFERENCES cart ( cart_id );

ALTER TABLE product_image
    ADD CONSTRAINT product_image_product_fk FOREIGN KEY ( product_id )
        REFERENCES product ( product_id );

CREATE SEQUENCE cart_product_id_SEQ 
START WITH 1 
    nocache order;

CREATE SEQUENCE product_image_id_SEQ 
START WITH 1 
    nocache order;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             3
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
